server:
  port: 8809
  servlet:
    context-path: /activiti-learning
spring:
  servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 15MB
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      indent-output: true
  datasource:
    #    jdbc-url: jdbc:mariadb://192.168.137.125:3306/employees?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
    jdbc-url: jdbc:mariadb://192.168.137.125:3306/employees?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    username: employees
    password: employees
    validationQuery: SELECT 1
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 200000
    max-lifetime: 200000
    connection-timeout: 50000
    connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy

  # activiti default configuration
  activiti:
    datasource:
      jdbc-url: jdbc:mariadb://192.168.137.125:3306/activiti_learning?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
      #    driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root
      validationQuery: SELECT 1
    #自动更新数据库结构
    # 1.flase：默认值。activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    # 2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    # 3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    # 4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    process-definition-location-suffixes:
      - '**.bpmn'
      - '**.bpmn20.xml'
    # 记录历史等级 可配置的历史级别有none, activity, audit, full
    # none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    # activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
    # audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
    # full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full
    async-executor-activate: true
    deploy-mode: never-fail # 关闭 SpringAutoDeployment

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

management:
  endpoints:
    web:
      cors:
        allowedOrigins:
          - ''
        allowedOriginPatterns:
          - ''
        allowedMethods:
          - ''
        allowedHeaders:
          - ''
        exposedHeaders:
          - ''
        allowCredentials: true
        maxAge: 600
